apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: r16a-z-grid
  namespace: r16a-z-grid
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - z-grid.r16a.cloud
      secretName: r16a-z-grid-tls
  rules:
    - host: z-grid.r16a.cloud
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: r16a-z-grid-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: r16a-z-grid-web
                port:
                  number: 80
