-- Grid enhancements
ALTER TABLE grids ADD COLUMN base_mva DOUBLE PRECISION DEFAULT 100.0;
ALTER TABLE grids ADD COLUMN frequency_hz DOUBLE PRECISION DEFAULT 60.0;

-- Bus enhancements
ALTER TABLE buses ADD COLUMN voltage_magnitude_pu DOUBLE PRECISION DEFAULT 1.0;
ALTER TABLE buses ADD COLUMN voltage_angle_deg DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE buses ADD COLUMN min_voltage_pu DOUBLE PRECISION DEFAULT 0.95;
ALTER TABLE buses ADD COLUMN max_voltage_pu DOUBLE PRECISION DEFAULT 1.05;
ALTER TABLE buses ADD COLUMN in_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE buses ADD COLUMN area INTEGER DEFAULT 1;
ALTER TABLE buses ADD COLUMN zone INTEGER DEFAULT 1;

-- Line enhancements
ALTER TABLE lines ADD COLUMN in_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE lines ADD COLUMN rating_mva_short_term DOUBLE PRECISION;
ALTER TABLE lines ADD COLUMN max_loading_percent DOUBLE PRECISION DEFAULT 100.0;

-- Transformer enhancements
ALTER TABLE transformers ADD COLUMN in_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE transformers ADD COLUMN sn_mva DOUBLE PRECISION;
ALTER TABLE transformers ADD COLUMN tap_min DOUBLE PRECISION DEFAULT 0.9;
ALTER TABLE transformers ADD COLUMN tap_max DOUBLE PRECISION DEFAULT 1.1;
ALTER TABLE transformers ADD COLUMN tap_step_percent DOUBLE PRECISION DEFAULT 1.25;
ALTER TABLE transformers ADD COLUMN tap_side VARCHAR(16) DEFAULT 'FROM';
ALTER TABLE transformers ADD COLUMN winding_type VARCHAR(16);
ALTER TABLE transformers ADD COLUMN max_loading_percent DOUBLE PRECISION DEFAULT 100.0;

-- Load enhancements
ALTER TABLE loads ADD COLUMN in_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE loads ADD COLUMN load_type VARCHAR(16) DEFAULT 'PQ';
ALTER TABLE loads ADD COLUMN scaling_factor DOUBLE PRECISION DEFAULT 1.0;

-- Generator enhancements
ALTER TABLE generators ADD COLUMN in_service BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE generators ADD COLUMN min_mvar DOUBLE PRECISION;
ALTER TABLE generators ADD COLUMN max_mvar DOUBLE PRECISION;
ALTER TABLE generators ADD COLUMN xdpp_pu DOUBLE PRECISION;
ALTER TABLE generators ADD COLUMN cost_a DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE generators ADD COLUMN cost_b DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE generators ADD COLUMN cost_c DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE generators ADD COLUMN ramp_rate_mw_per_min DOUBLE PRECISION;

-- Shunt compensators table
CREATE TABLE shunt_compensators (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bus_id UUID NOT NULL REFERENCES buses(id) ON DELETE CASCADE,
    name VARCHAR(255),
    shunt_type VARCHAR(16) NOT NULL,
    q_mvar DOUBLE PRECISION,
    max_step INTEGER DEFAULT 1,
    current_step INTEGER DEFAULT 1,
    in_service BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT shunt_type_check CHECK (shunt_type IN ('CAPACITOR', 'REACTOR'))
);

CREATE INDEX idx_shunt_compensators_bus_id ON shunt_compensators(bus_id);
