spring.application.name=zeus

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/zeus}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.bootstrap.admin.username=${DEFAULT_ADMIN_USERNAME:admin}
app.bootstrap.admin.password=${DEFAULT_ADMIN_PASSWORD:password}
app.bootstrap.admin.enabled=${DEFAULT_ADMIN_ENABLED:true}
app.bootstrap.team.name=${DEFAULT_TEAM_NAME:Default Team}
app.bootstrap.team.description=${DEFAULT_TEAM_DESCRIPTION:Default workspace team}
app.bootstrap.team.enabled=${DEFAULT_TEAM_ENABLED:true}